import type { Metadata } from "next";
import "./globals.css";
import Nav from "./constants/Nav"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="og:title" content="Little Lemon" />
        <meta name="og:description" content="Little Lemon is a family-owned medittarranean restaurant that exists in almost every part of the world, most notably: Chicago, LA, France, Italy, Sweden, Sarajevo, Hong Kong and many others." />
        <meta name="og:image" content="" />
      </head>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
